### ISSUE TITLE
NotImplementedError when using bitbang (non-SPI) pins on Raspberry Pi

### ISSUE THREAD

**Issue by PaintYourDragon** [adafruit/Adafruit_CircuitPython_WS2801#6]
Raspbian Buster Lite 2019-09-26, Pi 3 B, Python 3.7.3
Hardware SPI works OK. Attempting other pins throws NotImplementedError.

**Comment by makermelissa** [comment]
Here's the error output:
```
Traceback (most recent call last):
  File "ws2801_simpletest.py", line 14, in <module>
    leds = adafruit_ws2801.WS2801(oclock, odata, numleds, brightness=bright, auto_write=False)
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_ws2801.py", line 72, in __init__
    self._spi = busio.SPI(clock, MOSI=data)
  File "/home/pi/.local/lib/python3.7/site-packages/busio.py", line 100, in __init__
    format((clock, MOSI, MISO), spiPorts))
NotImplementedError: No Hardware SPI on (SCLK, MOSI, MISO)=(5, 6, None)
Valid SPI ports:((0, 11, 10, 9), (1, 21, 20, 19), (2, 42, 41, 40))
```
So, it looks like it attempts to run Hardware SPI and rather than being able to fallback to software bitbanging because it is only looking for a ValueError, it never even tries software. I think this was the correct place to file the issue and having it look for a NotImplementedError as well should fix it.

**Comment by ladyada** [comment]
blinka should throw a valueerror like other platforms

**Comment by makermelissa** [comment]
Ok, that would work too.

**Comment by makermelissa** [comment]
Created a PR that should fix this: https://github.com/adafruit/Adafruit_Blinka/pull/169
